// Generated by wxt
import 'wxt/browser';

declare module 'wxt/browser' {
    export type PublicPath =
        | ''
        | '/'
        | '/background.js'
        | '/icon.png'
        | '/icon.svg'
        | '/icons/icon-128.png'
        | '/icons/icon-16.png'
        | '/icons/icon-32.png'
        | '/icons/icon-48.png'
        | '/icons/icon.png'
        | '/icons/icon.svg'
        | '/popup.html'
        | '/vite.svg';
    type HtmlPublicPath = Extract<PublicPath, `${string}.html`>;
    export interface WxtRuntime {
        getURL(path: PublicPath): string;
        getURL(path: `${HtmlPublicPath}${string}`): string;
    }
}
